### PR TITLE
Remove iPad support

### PR DESCRIPTION
**Pull request by s8ngyu**

### CODE REVIEW

**Comment by sboh1214** [comment]
```
[03:46:17]: ----------------------------------
[03:46:17]: --- Step: upload_to_testflight ---
[03:46:17]: ----------------------------------
[03:46:17]: Login to App Store Connect (sboh021214@icloud.com)
[03:46:19]: Login successful
[03:46:20]: Ready to upload new build to TestFlight (App: 1579878255)...
[03:46:20]: Fetching password for transporter from environment variable named `FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD`
[03:46:23]: Fetching password for transporter from environment variable named `FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD`
[03:46:23]: Going to upload updated app to App Store Connect
[03:46:23]: This might take a few minutes. Please don't interrupt the script.
[03:47:25]: [altool] 2023-07-24 03:47:25.179 *** Error: Asset validation failed This bundle does not support one or more of the devices supported by the previous app version. Your app update must continue to support all devices previously supported. You declare supported devices in Xcode with the Targeted Device Family build setting. Refer to QA1623 for additional information: https://developer.apple.com/library/ios/#qa/qa1623/_index.html (ID: 2a038137-1092-4b6b-8021-65232ce101ab) (90101)

[03:47:25]: [altool]  {

[03:47:25]: [altool]     NSLocalizedDescription = "Asset validation failed";

[03:47:25]: [altool]     NSLocalizedFailureReason = "This bundle does not support one or more of the devices supported by the previous app version. Your app update must continue to support all devices previously supported. You declare supported devices in Xcode with the Targeted Device Family build setting. Refer to QA1623 for additional information: https://developer.apple.com/library/ios/#qa/qa1623/_index.html (ID: 2a038137-1092-4b6b-8021-65232ce101ab)";

[03:47:25]: [altool]     "original_server_error" =     {

[03:47:25]: [altool]         code = "STATE_ERROR.VALIDATION_ERROR.90101";

[03:47:25]: [altool]         detail = "This bundle does not support one or more of the devices supported by the previous app version. Your app update must continue to support all devices previously supported. You declare supported devices in Xcode with the Targeted Device Family build setting. Refer to QA1623 for additional information: https://developer.apple.com/library/ios/#qa/qa1623/_index.html";

[03:47:25]: [altool]         id = "2a038137-1092-4b6b-8021-65232ce101ab";

[03:47:25]: [altool]         status = 409;

[03:47:25]: [altool]         title = "Asset validation failed";

[03:47:25]: [altool]     };

[03:47:25]: [altool] }

[03:47:25]: Application Loader output above ^
[03:47:25]: ERROR: Asset validation failed (90101) This bundle does not support one or more of the devices supported by the previous app version. Your app update must continue to support all devices previously supported. You declare supported devices in Xcode with the Targeted Device Family build setting. Refer to QA1623 for additional information: https://developer.apple.com/library/ios/#qa/qa1623/_index.html (ID: 2a038137-1092-4b6b-8021-65232ce101ab)
[03:47:25]: Error uploading '/var/folders/90/_s0h7d6n667dd54rrndn_28r0000gn/T/3a9c0ac4-ede3-48cb-a6a9-612ae9dbae6d.ipa'.
[03:47:25]: Asset validation failed This bundle does not support one or more of the devices supported by the previous app version. Your app update must continue to support all devices previously supported. You declare supported devices in Xcode with the Targeted Device Family build setting. Refer to QA1623 for additional information: https://developer.apple.com/library/ios/#qa/qa1623/_index.html (ID: 2a038137-1092-4b6b-8021-65232ce101ab) (90101)
[03:47:25]: The call to the altool completed with a non-zero exit status: 1. This indicates a failure.
[03:47:25]: Could not download/upload from App Store Connect!
+--------------------+-----------------------------------------------------------------+
|                                     Lane Context                                     |
+--------------------+-----------------------------------------------------------------+
| DEFAULT_PLATFORM   | ios                                                             |
| PLATFORM_NAME      | ios                                                             |
| LANE_NAME          | ios alpha                                                       |
| BUILD_NUMBER       | 230724.0344                                                     |
| IPA_OUTPUT_PATH    | /Users/sboh/Repos/otl-app/ios/Runner.ipa                        |
| XCODEBUILD_ARCHIVE | /Users/sboh/Library/Developer/Xcode/Archives/2023-07-24/Runner  |
|                    | 2023-07-24 03.44.57.xcarchive                                   |
| DSYM_OUTPUT_PATH   | /Users/sboh/Repos/otl-app/ios/Runner.app.dSYM.zip               |
+--------------------+-----------------------------------------------------------------+
[03:47:25]: Error uploading ipa file: 
 [Application Loader Error Output]: ERROR: Asset validation failed (90101) This bundle does not support one or more of the devices supported by the previous app version. Your app update must continue to support all devices previously supported. You declare supported devices in Xcode with the Targeted Device Family build setting. Refer to QA1623 for additional information: https://developer.apple.com/library/ios/#qa/qa1623/_index.html (ID: 2a038137-1092-4b6b-8021-65232ce101ab)
[Application Loader Error Output]: Error uploading '/var/folders/90/_s0h7d6n667dd54rrndn_28r0000gn/T/3a9c0ac4-ede3-48cb-a6a9-612ae9dbae6d.ipa'.
[Application Loader Error Output]: Asset validation failed This bundle does not support one or more of the devices supported by the previous app version. Your app update must continue to support all devices previously supported. You declare supported devices in Xcode with the Targeted Device Family build setting. Refer to QA1623 for additional information: https://developer.apple.com/library/ios/#qa/qa1623/_index.html (ID: 2a038137-1092-4b6b-8021-65232ce101ab) (90101)
[Application Loader Error Output]: The call to the altool completed with a non-zero exit status: 1. This indicates a failure.
```

**Comment by s8ngyu** [comment]
device family drop support가 안 되나요..? 새 빌드 말고 새 버전으로 하면 될 것 같긴 한데..

**Comment by sboh1214** [comment]
삭제하지 않는 이상 안되는거 같기도 하네요...
https://developer.apple.com/library/archive/qa/qa1623/_index.html

Replacing Your App in the Store

Removing your app from the store, and uploading the update with a different bundle ID, will   allow you to narrow the range of devices your update supports. However the update will be   listed on the store as a separate app. Existing users of your app must purchase the update   through the App Store, just like new customers.

Because the update will be treated as a different app, it must have a different name in iTunes Connect than the name of the app already in the store.

**Comment by s8ngyu** [comment]
새로운 생태계에 한 번 발을 잘못 딛으면 빠져나올 수가 없는.. 끔찍하네요..

**Comment by sboh1214** [comment]
iPadOS 지원을 포기하는 건 불가능할 것 같아서 일단 PR 닫겠습니다.
> Your app update must continue to support all devices previously supported.

**Pull request closed without merging**
